spring:
  application:
    name: psicologia

  datasource:
    url: jdbc:postgresql://localhost:5432/psicologia
    username: postgres
    password: arthur15

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080